all:
	gcc -o KeyboardDaemon src/KeyboardDaemon.c src/Daemonize.c src/KeyboardInterface.c src/ReadMatrix.c -lwiringPi
#	gcc -std=c99 -lwiringPi src/KeyboardDaemon.c src/Daemonize.c src/KeyboardInterface.c src/ReadMatrix.c -o KeyboardDaemon
